version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
before_build: nuget restore
build: 
    project: E:\Programming\.NET\AppVeyorHomeWork\FromEmptyToMVC\FromEmptyToMVC.csproj
    publish_wap: true